FORMAT: 1A

# Caravelo Test API
Implementation of Market Survey for test purposes

## Media Types
Requests with a message-body are using plain JSON to set or update resource states.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

## Data Structures
:[](datastructures/tag.mson)
:[](datastructures/question.mson)
:[](datastructures/answer.mson)
:[](datastructures/poll.mson)
:[](datastructures/survey.mson)


:[](resources/survey.apib)
:[](resources/poll.apib)