# Group Poll

Provides an interface to send Market Survey results.

## surveys [/survey/{tag}/poll]

+ Parameters
    + tag: tag-slug (string) - tag slug for filter

## Create Poll [PUT]
This resource could lead to a redirect to Buy-Ship-Pay process

+ Request
    + Attributes (Poll)

+ Response 201
+ Response 307
+ Response 400