# Group Survey

Market Surveys availables on our systems. You can use tags to filter

## surveys [/surveys]

+ Parameters
    + tag: not required (string) - tag slug for filter

## Get Surveys [GET]

+ Response 200 (text/json)

    + Attributes (array[Survey])

## survey [/survey/{slug}]

+ Parameters

    + slug: test-survey (number)

## Get Survey [GET]

+ Response 200 (text/json)

    + Attributes (Survey)

+ Response 404
